language: node_js

before_install:
- npm install -g grunt-cli
- gem install sass

script:
- grunt

after_script:
- npm run coverage

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b90b361c0bc91a778bcc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
